/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerCellIdRouteImport } from './routes/viewer.$cellId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerCellIdRoute = ViewerCellIdRouteImport.update({
  id: '/viewer/$cellId',
  path: '/viewer/$cellId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/viewer/$cellId': typeof ViewerCellIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/viewer/$cellId': typeof ViewerCellIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/viewer/$cellId': typeof ViewerCellIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/viewer/$cellId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/viewer/$cellId'
  id: '__root__' | '/' | '/viewer/$cellId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewerCellIdRoute: typeof ViewerCellIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$cellId': {
      id: '/viewer/$cellId'
      path: '/viewer/$cellId'
      fullPath: '/viewer/$cellId'
      preLoaderRoute: typeof ViewerCellIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewerCellIdRoute: ViewerCellIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
